
obj-y += stdstreams.o

obj-y += \
	fopen.o \
	fclose.o

obj-y += \
	fputc.o \
	putc.o \
	putchar.o \
	fputs.o \
	puts.o

obj-y += \
	fseek.o \
	ftell.o

obj-y += \
	fgetc.o \
	getc.o \
	getchar.o \
	fgets.o

obj-y += \
	fread.o \
	fwrite.o \
	fflush.o

obj-y += \
	doprnt.o \
	vfprintf.o \
	fprintf.o \
	printf.o \
	vsnprintf.o \
	snprintf.o \

obj-y += \
	doscan.o \
	vfscanf.o \
	fscanf.o \
	scanf.o \

obj-y += \
	remove.o \
	rename.o \

obj-y += perror.o

