
obj-y += \
	abort.o \
	exit.o \
	atexit.o \
	abs.o \
	labs.o \
	llabs.o \
	strtoll.o \
	strtol.o \
	strtoull.o \
	strtoul.o \
	atoll.o \
	atol.o \
	atoi.o \
	system.o \
	getenv.o \
	setenv.o \
	qsort.o \
	mmap_alloc/

