
obj-y += \
	abort.o \
	exit.o \
	atexit.o \
	abs.o \
	labs.o \
	llabs.o \
	strtoll.o \
	strtol.o \
	strtoull.o \
	strtoul.o \
	atoll.o \
	atol.o \
	atoi.o \
	strtod.o \
	atof.o \
	system.o \
	getenv.o \
	setenv.o \
	putenv.o \
	unsetenv.o \
	qsort.o \


obj-$(CONFIG_MMAP_ALLOC) += mmap_alloc/

