
obj-y += \
	opcode.o \
	state.o \
	name.o \
	pkglength.o \
	namespace.o \
	term_arg.o \
	string.o \
	scope.o \
	named_reference.o \
	def_op_region.o \
	def_field.o \
	def_method.o \
	def_device.o \
	def_processor.o \
	def_thermal_zone.o \
	def_power_resource.o \
	def_name.o \
	def_alias.o \
	def_mutex.o \
	def_buffer.o \
	def_package.o \
	def_varpackage.o \
	def_create_field.o \

