
obj-y += \
	close.o \
	fork.o \
	dup.o \
	dup2.o \
	pipe.o \
	chdir.o \
	chroot.o \
	execvp.o \
	sleep.o \
	usleep.o \
	unlink.o \
	getcwd.o \
	write.o \
	read.o \
	access.o \
	lseek.o \
	isatty.o \
	fsync.o \
	link.o \
	symlink.o \
	readlink.o \

obj-$(CONFIG_X64) += x64_fork_impl.o
obj-$(CONFIG_RISCV64) += riscv64_fork_impl.o
