
ifdef CONFIG_X64
KERNEL_CROSS_COMPILE_PREFIX ?=
USER_CROSS_COMPILE_PREFIX ?= x86_64-kanawha-
endif
ifdef CONFIG_RISCV64
KERNEL_CROSS_COMPILE_PREFIX ?= riscv64-unknown-elf-
USER_CROSS_COMPILE_PREFIX ?= riscv64-unknown-elf-
endif
ifdef CONFIG_ARM64
KERNEL_CROSS_COMPILE_PREFIX ?= aarch64-linux-gnu-
USER_CROSS_COMPILE_PREFIX ?= aarch64-linux-gnu-
USER_COMMON_FLAGS += -ffreestanding
endif


CC  := gcc
CPP := cpp
LD  := ld
AS  := gcc

OBJCOPY := objcopy
OBJDUMP := objdump

KERNEL_CC      := $(KERNEL_CROSS_COMPILE_PREFIX)$(CC)
KERNEL_CPP     := $(KERNEL_CROSS_COMPILE_PREFIX)$(CPP)
KERNEL_LD      := $(KERNEL_CROSS_COMPILE_PREFIX)$(LD)
KERNEL_AS      := $(KERNEL_CROSS_COMPILE_PREFIX)$(AS)
KERNEL_OBJCOPY := $(KERNEL_CROSS_COMPILE_PREFIX)$(OBJCOPY)
KERNEL_OBJDUMP := $(KERNEL_CROSS_COMPILE_PREFIX)$(OBJDUMP)

USER_CC      := $(USER_CROSS_COMPILE_PREFIX)$(CC)
USER_CPP     := $(USER_CROSS_COMPILE_PREFIX)$(CPP)
USER_LD      := $(USER_CROSS_COMPILE_PREFIX)$(LD)
USER_AS      := $(USER_CROSS_COMPILE_PREFIX)$(AS)
USER_OBJCOPY := $(USER_CROSS_COMPILE_PREFIX)$(OBJCOPY)
USER_OBJDUMP := $(USER_CROSS_COMPILE_PREFIX)$(OBJDUMP)

# For some reason ARM64 is having trouble finding libgcc
# on my current system (IDK why) -KJH
ifdef CONFIG_ARM64
ARM64_LIBGCC_PATH = $(shell $(KERNEL_CC) -print-libgcc-file-name)
KERNEL_LDFLAGS += -L$(dir $(ARM64_LIBGCC_PATH)) -lgcc
endif
