
obj-y += \
	memcpy.o \
	memmove.o \
	strcpy.o \
	strncpy.o \
	strcat.o \
	strncat.o \
	memcmp.o \
	strcmp.o \
	strcoll.o \
	strncmp.o \
	strxfrm.o \
	memchr.o \
	strchr.o \
	strchrnul.o \
	strcspn.o \
	strpbrk.o \
	strrchr.o \
	strspn.o \
	strstr.o \
	strtok.o \
	memset.o \
	strerror.o \
	strlen.o \
	strnlen.o \
	strdup.o \
	strndup.o \
	strncasecmp.o \
	strcasecmp.o \
	stpcpy.o \
	mempcpy.o \
	memrchr.o \
	strsignal.o \

