
obj-y += handlers.o
obj-y += \
	signal.o \
	kill.o \
	killpg.o \
	raise.o \

obj-y += \
	sigaction.o \
	sigprocmask.o \
	sigemptyset.o \
	sigfillset.o \
	sigaddset.o \
	sigdelset.o \
	sigismember.o \
	sigsuspend.o \

obj-y += \
	sigisemptyset.o \
	sigorset.o \
	sigandset.o \

