
obj-y += \
	ptree.o \
	stree.o \
	buddy.o \
	file.o \
	kheap.o \
	kmalloc.o \
	printk.o \
	mem_flags.o \
	page_alloc.o \
	vmem.o \
	slab.o \
	init.o \
	errno.o \
	common.o \
	bitmap.o \
	device.o \
	ramfile.o \
	char_dev.o \
	irq_domain.o \
	irq_dev.o \
	thread.o \
	scheduler.o \
	usermode.o \
	syscall.o \
	process.o \
	env.o \
	cpu.o \
	percpu.o \
	mmio.o \
	symbol.o \
	module.o \
	string.o \
	waitqueue.o \
	pipe.o \
	xcall.o \
	timer.o \
	spinlock.o \
	clk.o \
	kbd.o

obj-y += fs/
obj-y += syscall/
obj-y += drivers/
obj-y += sched/
obj-y += elf/
obj-y += mb2/
obj-$(CONFIG_ACPI) += acpi/

