
obj-y += \
	ptree.o \
	stree.o \
	ref.o \
	buddy.o \
	kheap.o \
	printk.o \
	klog.o \
	mem_flags.o \
	page_alloc.o \
	vmem.o \
	slab.o \
	init.o \
	errno.o \
	excp.o \
	common.o \
	bitmap.o \
	ramfile.o \
	irq_domain.o \
	thread.o \
	scheduler.o \
	tasklet.o \
	usermode.o \
	syscall.o \
	exec_type.o \
	mmio.o \
	dma.o \
	symbol.o \
	module.o \
	string.o \
	parse.o \
	waitqueue.o \
	socket.o \
	xcall.o \
	time.o \
	event.o \
	sleep.o \
	spinlock.o \
	clk.o \
	kbd.o \
	strace.o \
	udrv.o \
	perf.o \
	lock.o \

obj-y += stack.o

obj-y += cpu/
obj-y += kmalloc/
obj-y += dev/
obj-y += fs/
obj-y += syscall/
obj-y += sched/
obj-y += elf/
obj-y += mb2/
obj-y += proc/
obj-y += net/
obj-y += sysfs/
obj-y += gfx/
obj-y += panic/
obj-$(CONFIG_PAGING) += paging/

obj-y += memdump.o

obj-$(CONFIG_ACPI) += acpi/
obj-$(CONFIG_DEVICETREE) += devtree/

