
obj-y += \
	ptree.o \
	stree.o \
	buddy.o \
	kheap.o \
	kmalloc/ \
	printk.o \
	klog.o \
	mem_flags.o \
	page_alloc.o \
	vmem.o \
	slab.o \
	init.o \
	errno.o \
	common.o \
	bitmap.o \
	ramfile.o \
	rand_dev.o \
	irq_domain.o \
	irq_dev.o \
	thread.o \
	scheduler.o \
	usermode.o \
	syscall.o \
	cpu.o \
	percpu.o \
	mmio.o \
	dma.o \
	symbol.o \
	module.o \
	string.o \
	parse.o \
	waitqueue.o \
	pipe.o \
	xcall.o \
	timer.o \
	time.o \
	event.o \
	sleep.o \
	spinlock.o \
	clk.o \
	kbd.o \
	strace.o

obj-y += stack.o

obj-y += dev/
obj-y += fs/
obj-y += syscall/
obj-y += sched/
obj-y += elf/
obj-y += mb2/
obj-y += proc/
obj-y += net/
obj-y += linux/

obj-y += memdump.o

obj-$(CONFIG_ACPI) += acpi/
obj-$(CONFIG_DEVICETREE) += devtree/

