
obj-y += \
	longjmp.o \

obj-$(CONFIG_X64) += \
	x64_setjmp.o \
	x64_longjmp.o \

obj-$(CONFIG_RISCV64) += \
	riscv64_setjmp.o \
	riscv64_longjmp.o \

obj-$(CONFIG_ARM64) += \
	arm64_setjmp.o \
	arm64_longjmp.o \

