
obj-y += \
	acpi.o \

obj-y += \
	fadt_tables.o \

obj-$(CONFIG_ACPI_INTERPRET_AML) += \
	dsdt.o \
	namespace.o \
	name.o \
	object.o \
	interp.o \
	interp/ \


obj-$(CONFIG_ACPI_SYSFS) += \
	sysfs.o \

