
obj-y += \
	blk/ \
	term/ \
	rand/ \
	net/ \
	clk/ \
	qemu/ \
	fb/ \
	irq/ \
	fs/ \
	kbd/ \
	snd/ \

obj-y += \
	pci/ \
	virtio/ \
	usb/ \

obj-y += linux/

obj-$(CONFIG_PORT_IO) += vga/

obj-$(CONFIG_PS2) += ps2/

