
obj-y += \
	blk/ \
	term/ \
	rand/ \
	net/ \
	clk/ \
	timer/ \
	qemu/ \
	fb/ \
	irq/ \
	fs/ \
	input/ \
	snd/ \

obj-y += \
	pci/ \
	virtio/ \
	usb/ \
	scsi/ \

obj-y += linux/

obj-$(CONFIG_VGA) += vga/

obj-$(CONFIG_PS2) += ps2/

