
obj-y += stdstreams.o

obj-y += fileno.o

obj-y += \
	fopen.o \
	fclose.o \
	freopen.o \
	fdopen.o \
	dofopen.o \

obj-y += \
	fputc.o \
	putc.o \
	putchar.o \
	fputs.o \
	puts.o

obj-y += \
	fseek.o \
	ftell.o \
	fseeko.o \
	ftello.o \

obj-y += \
	fgetc.o \
	getc.o \
	ungetc.o \
	getchar.o \
	fgets.o

obj-y += \
	fread.o \
	fwrite.o \
	fflush.o

obj-y += \
	fsetpos.o \
	fgetpos.o \

obj-y += \
	doprnt.o \
	vfprintf.o \
	fprintf.o \
	printf.o \
	vsnprintf.o \
	snprintf.o \
	sprintf.o \
	asprintf.o \
	vasprintf.o \

obj-y += \
	doscan.o \
	vfscanf.o \
	fscanf.o \
	vsscanf.o \
	sscanf.o \
	scanf.o \

obj-y += \
	remove.o \
	rename.o \

obj-y += \
	ferror.o \
	feof.o \
	clearerr.o \

obj-y += perror.o

obj-y += rewind.o

obj-y += \
	tmpnam.o \
	tmpfile.o \

obj-y += \
	setbuf.o \
	setvbuf.o \
	setlinebuf.o \

obj-y += \
	popen.o \
	pclose.o \

obj-y += \
	flockfile.o \
	funlockfile.o \
	ftrylockfile.o \

