
obj-y += \
	ctx.o \
	name.o \
	opcode.o \
	pkg_length.o \
	constants.o \
	term.o \
	data_obj.o \
	local_obj.o \
	expression.o \
	logical_op.o \
	arith_op.o \
	statement.o \
	named_obj.o \
	op_region.o \
	namespace_modifier.o \
	invoke.o \
	target.o \

