
obj-$(CONFIG_PCI) += pci.o

pci-y += \
	cfg.o \
	bar.o \
	cap.o \
	match.o \
	bus.o \
	device.o \
	func.o \
	irq.o \
	msi.o \
	msix.o \
	mailbox.o

pci-$(CONFIG_PCI_PORT_CAM) += port_cam.o

pci-$(CONFIG_SYSFS_PCI) += sysfs.o

