
obj-y += \
	string/ \
	stdlib/ \
	stdio/ \
	stdio_ext/ \
	time/ \
	ctype/ \
	signal/ \
	setjmp/ \
	getopt.o \
	locale.o \
	errno.o \
	posix/ \
	argv.o \
	sgtty.o \
	byteswap.o \
	endian.o \
	fenv.o \

obj-$(CONFIG_X64) += x64_syscall.o
obj-$(CONFIG_RISCV64) += riscv64_syscall.o

