site_name: Kanawha Kernel Documentation
theme:
  name: terminal
  palette: dark

nav:
  - Home: index.md
  - Documentation:
    - buildsystem/index.md
    - interfaces/index.md
    - arch/index.md
  - Contributors: contributors.md

plugins:
- search
