#ifndef __ELK_POSIX__LANGINFO_H__
#define __ELK_POSIX__LANGINFO_H__

#include <nl_types.h>

#define __LANGINFO_BASE (0)

#define  CODESET      (nl_item)(__LANGINFO_BASE + 0)
#define  D_T_FMT      (nl_item)(__LANGINFO_BASE + 1)
#define  D_FMT        (nl_item)(__LANGINFO_BASE + 2)
#define  T_FMT        (nl_item)(__LANGINFO_BASE + 3)
#define  T_FMT_AMPM   (nl_item)(__LANGINFO_BASE + 4)
#define  AM_STR       (nl_item)(__LANGINFO_BASE + 5)
#define  PM_STR       (nl_item)(__LANGINFO_BASE + 6)
#define  DAY_1        (nl_item)(__LANGINFO_BASE + 7)
#define  DAY_2        (nl_item)(__LANGINFO_BASE + 8)
#define  DAY_3        (nl_item)(__LANGINFO_BASE + 9)
#define  DAY_4        (nl_item)(__LANGINFO_BASE + 10)
#define  DAY_5        (nl_item)(__LANGINFO_BASE + 11)
#define  DAY_6        (nl_item)(__LANGINFO_BASE + 12)
#define  DAY_7        (nl_item)(__LANGINFO_BASE + 13)
#define  ABDAY_1      (nl_item)(__LANGINFO_BASE + 14)
#define  ABDAY_2      (nl_item)(__LANGINFO_BASE + 15)
#define  ABDAY_3      (nl_item)(__LANGINFO_BASE + 16)
#define  ABDAY_4      (nl_item)(__LANGINFO_BASE + 17)
#define  ABDAY_5      (nl_item)(__LANGINFO_BASE + 18)
#define  ABDAY_6      (nl_item)(__LANGINFO_BASE + 19)
#define  ABDAY_7      (nl_item)(__LANGINFO_BASE + 20)
#define  MON_1        (nl_item)(__LANGINFO_BASE + 21)
#define  MON_2        (nl_item)(__LANGINFO_BASE + 22)
#define  MON_3        (nl_item)(__LANGINFO_BASE + 23)
#define  MON_4        (nl_item)(__LANGINFO_BASE + 24)
#define  MON_5        (nl_item)(__LANGINFO_BASE + 25)
#define  MON_6        (nl_item)(__LANGINFO_BASE + 26)
#define  MON_7        (nl_item)(__LANGINFO_BASE + 27)
#define  MON_8        (nl_item)(__LANGINFO_BASE + 28)
#define  MON_9        (nl_item)(__LANGINFO_BASE + 29)
#define  MON_10       (nl_item)(__LANGINFO_BASE + 30)
#define  MON_11       (nl_item)(__LANGINFO_BASE + 31)
#define  MON_12       (nl_item)(__LANGINFO_BASE + 32)
#define  ABMON_1      (nl_item)(__LANGINFO_BASE + 33)
#define  ABMON_2      (nl_item)(__LANGINFO_BASE + 34)
#define  ABMON_3      (nl_item)(__LANGINFO_BASE + 35)
#define  ABMON_4      (nl_item)(__LANGINFO_BASE + 36)
#define  ABMON_5      (nl_item)(__LANGINFO_BASE + 37)
#define  ABMON_6      (nl_item)(__LANGINFO_BASE + 38)
#define  ABMON_7      (nl_item)(__LANGINFO_BASE + 39)
#define  ABMON_8      (nl_item)(__LANGINFO_BASE + 40)
#define  ABMON_9      (nl_item)(__LANGINFO_BASE + 41)
#define  ABMON_10     (nl_item)(__LANGINFO_BASE + 42)
#define  ABMON_11     (nl_item)(__LANGINFO_BASE + 43)
#define  ABMON_12     (nl_item)(__LANGINFO_BASE + 44)
#define  ERA          (nl_item)(__LANGINFO_BASE + 45)
#define  ERA_D_FMT    (nl_item)(__LANGINFO_BASE + 46)
#define  ERA_D_T_FMT  (nl_item)(__LANGINFO_BASE + 47)
#define  ERA_T_FMT    (nl_item)(__LANGINFO_BASE + 48)
#define  ALT_DIGITS   (nl_item)(__LANGINFO_BASE + 49)
#define  RADIXCHAR    (nl_item)(__LANGINFO_BASE + 50)
#define  THOUSEP      (nl_item)(__LANGINFO_BASE + 51)
#define  YESEXPR      (nl_item)(__LANGINFO_BASE + 52)
#define  NOEXPR       (nl_item)(__LANGINFO_BASE + 53)
#define  CRNCYSTR     (nl_item)(__LANGINFO_BASE + 54)

char *nl_langinfo(nl_item);

#endif
