
obj-y += \
    exit.o \
	open.o \
	close.o \
	read.o \
	write.o \
	seek.o \
	mmap.o \
	exec.o \
	environ.o \
	spawn.o \
	reap.o \
	getpid.o \
	mount.o \
	dir.o \
	fswap.o \
	mkfile.o \
	mkfifo.o \
	mkdir.o \
	link.o \
	symlink.o \
	unlink.o

