
obj-y += \
    exit.o \
	open.o \
	close.o \
	read.o \
	write.o \
	flush.o \
	seek.o \
	mmap.o \
	exec.o \
	environ.o \
	getcwd.o \
	spawn.o \
	reap.o \
	getpid.o \
	mount.o \
	dirbegin.o \
	dirnext.o \
	dirattr.o \
	dirname.o \
	fmove.o \
	fattr.o \
	mkfile.o \
	mkdir.o \
	pipe.o \
	link.o \
	symlink.o \
	unlink.o \
	chroot.o \
	chwdir.o \
	mod.o \
	sleep.o \
	time.o \
	sigret.o \
	sigroute.o \

