
libs += \
	crt \
	c \
	dl \
	kfb \
	ksnd \
	windd \
	sock \
	bark \

bins += \
	init \
	randd \
	windd \
	barkd \

bins += \
    cat \
    cowsay \
    dumpenv \
    fbinfo \
    hexdump \
    ls \
    lspci \
    mkudrv \
    mount \
    rm \
    seat \
    sh \
    stress \
    udrv_term \
    xlateinput \
    colors \
    cp \
    fault \
    fbterm \
    insmod \
    lsacpi \
    mkdir \
    more \
    nettest \
    rmmod \
    set \
    sleep \
    udrv_rand \
    write \
	wintest \
	sysplot \
	ps \
	klog \
	beep \

