
libs += \
	crt \
	c \
	dl \
	kfb \

bins += \
    cat \
    cowsay \
    dumpenv \
    fbinfo \
    hexdump \
    ls \
    lspci \
    mkudrv \
    mount \
    rm \
    seat \
    sh \
    stress \
    udrv_term \
    xlateinput \
    colors \
    cp \
    fault \
    fbterm \
    insmod \
    lsacpi \
    mkdir \
    more \
    nettest \
    rmmod \
    set \
    sleep \
    udrv_rand \
    write

