
obj-y += asm/

obj-y += \
	init.o \
	identity_map.o \
	irq.o \
	vmem.o \
	common.o \
	thread.o \
	usermode.o \
	percpu.o \
	cpu.o \
	mem_flags.o \
	trap.o \
	page_fault.o \
	sbi_console.o \
	sbi_ipi.o \
	sbi_timer.o \
	sbi_hsm.o \
	hlic.o \
	smp.o \

